### ISSUE TITLE
Reference to libPlugin in the readme

### ISSUE THREAD

**Issue by mfrigerio17** [CoppeliaRobotics/simExtROS2Interface#17]
Hi, the readme of this repository refers to the documentation of libPlugin, but that does not exist anymore. The new repository [include.git](https://github.com/CoppeliaRobotics/include) does not have a readme...
So it is not clear which are the dependencies to be installed in step 1

**Comment by Coppelia** [comment]
Hello,

for release V4.5, we have merged several repositories into the include repository (including common, libPlugin and simMath). Because of that, make sure to pull the branch corresponding to your CoppeliaSim version. E.g. for the last version, V4.4, use coppeliasim-v4.4.0-rev0, i.e. git clone -b coppeliasim-v4.4.0-rev0 https://github.com/CoppeliaRobotics/libPlugin

Cheers
